(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



BeginPackage["abinittools`"]
Unprotect@@Names["abinittools`*"];
ClearAll@@Names["abinittools`*"];


AbinitEVPlotData::usage="AbinitEVPlotData: Generates a List, plottable with ListPlot, from an eigenvalue output file from ABINIT (e.g. \"systemname_DS2_EIG\"). Plotdata, number of bands and number of k-points are returned.";


Begin["`Private`"]


AbinitEVPlotData[file_]:=Module[{data,plotdata,nbands,kpoints,evlines},
data=Import[file,"Table"];
nbands=ToExpression[StringDrop[data[[2,4]],-1]];
kpoints=data[[1,7]];
evlines=Ceiling[nbands/8];
plotdata=Table[Flatten[data[[i;;i+evlines-1]] ],{i,3,(evlines+1) kpoints,evlines+1}]//Transpose;
{plotdata,nbands,kpoints}
];


End[]
Protect@@Names["abinittools`*"];
EndPackage[]
